# Set up how we will call Ledger
ledger_file: /path/to/ledger.journal
ledger_args: ['--pedantic', '--recursive-aliases']
report_commodity: '$'

# Tell ledger-pyreport about the top-level account categories
assets_account: Assets
liabilities_account: Liabilities
equity_account: Equity
income_account: Income
expenses_account: Expenses
oci_account: OCI # Other Comprehensive Income

# These income and expense categories appear separately on the income statement
separate_pandl: []

# These accounts will automatically be populated on reports
unrealized_gains: ['OCI:Unrealized Gains', 'OCI: Unrealized Losses']

accumulated_oci: 'Equity:Accumulated Other Comprehensive Income'
current_year_oci: 'Equity:Current Year Other Comprehensive Income'
retained_earnings: 'Equity:Retained Earnings'
current_year_earnings: 'Equity:Current Year Earnings'

# Which asset accounts to consider in cash basis mode
cash_asset_accounts: ['Assets:Current:Cash on Hand', 'Assets:Current:Cash at Bank']
# Which account to charge non-cash transactions to in cash basis mode, when no other account is suitable
cash_other_income: 'Income:Other Income'

# Extensions to load
extensions: []
