# Set up how we will call Ledger
ledger_file: demo/ledger.journal
ledger_args: []
report_currency: ['$', True] # True if prefix, False if suffix

# Tell ledger-pyreport about the top-level account categories
assets_account: Assets
liabilities_account: Liabilities
equity_account: Equity
income_account: Income
expenses_account: Expenses

# These accounts will automatically be populated on reports
unrealized_gains: 'Equity:Unrealized Gains'
retained_earnings: 'Equity:Retained Earnings'
current_year_earnings: 'Equity:Current Year Earnings'

# Which asset accounts to consider in cash basis mode
cash_asset_accounts: ['Assets:Current:Cash on Hand', 'Assets:Current:Cash at Bank', 'Assets:Current:International Account']
# Which account to charge non-cash transactions to in cash basis mode, when no other account is suitable
cash_other_income: 'Income:Other Income'
