---
name: Build
permissions:
  contents: read
  pull-requests: write

on: pull_request

jobs:
  build:
    uses: obscurerichard/ledger-pyreport/.github/workflows/build-docker.yml@0.1.1
    with:
      tag: latest-actions-build
    secrets: inherit
