---
name: Build Latest
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - 'main'

jobs:

  build:
    uses: obscurerichard/ledger-pyreport/.github/workflows/build-docker.yml@0.1.1
    with:
      tag: latest
    secrets: inherit

