---
name: Docker Build and maybe Push

on: 
  workflow_call:
    inputs:
      org:
        default: obscurerichard
        description: 'Docker Hub organization'
        required: false
        type: string
      repo:
        default: ledger-pyreport
        description: 'Docker Hub repository name'
        required: false
        type: string
      tag:
        default: latest
        description: 'tag for Docker container'
        required: false
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        # Thanks https://stackoverflow.com/a/71854535/424301
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ inputs.org }}/${{ inputs.repo }}:${{ inputs.tag }}
      -
        name: Build and push
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ inputs.org }}/${{ inputs.repo }}:${{ inputs.tag }}

