---
name: Lint

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: fawltydeps lint
        uses: tweag/FawltyDeps-action@v0.1.0
        with:
          options: --list-imports --list-deps --detailed
